name: Provision t2.micro EC2

on:
  workflow_dispatch:
    inputs:
      ec2_name:
        description: EC2 name
        required: true
        default: 'ExampleAppServerInstance'
        type: string

jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Apply
        id: apply
        env:
          EC2_NAME: ${{ github.event.inputs.ec2_name }}
        run: |
          cd provider.tf/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
